### ISSUE TITLE
Dec Vt220 

### ISSUE THREAD

**Issue by TheWanderer1983** [mezantrop/sclocka#2]
Hello, 

I have a green dec vt220 terminal which I thought would be great to use the matrix screensaver to limit burn in. I originally found ascii saver but thought this might better suited for a lock screen. Any chance you could incorporate cmatrix as a option for sclocka?

Regards
Dylan

**Comment by mezantrop** [comment]
Hello Dylan, I also first found your question on the blog and answered there.
Anyway, it's an interesting idea. No promises, on when and where, but I'll see what I can do about that i.e. run external processes/plugins to play animation.

Best,
Mike

**Comment by mezantrop** [comment]
![sclocka-cmatrix](https://github.com/user-attachments/assets/e8f598a2-74b1-4e6c-873c-548d6efee758)

@TheWanderer1983 Did you mean something like that?

**Comment by TheWanderer1983** [comment]
That looks great. I'll have to try it on the DEC.

**Comment by mezantrop** [comment]
Ok, I'll add smth like: [-e /path/to/binary/saver args] to the CLI options. But, sorry for the disclaimer: beware, that probably not all the external screensavers will work as expected, also they may crash and overall consequences could be unexpected or potentially dangerous. Anyway, I'll have time the next week to make all the required changes.

**Comment by TheWanderer1983** [comment]
That's fine. Thanks again.

**Comment by mezantrop** [comment]
You can try it now and let me know if it works.

**Comment by TheWanderer1983** [comment]
Okay, sort of works for me. If i run it -E '/usr/local/bin/cmatrix' it loads but I can't exit out as its not screensaver mode. If i run it with -s it doesn't load it just shows me a blinking cursor, and if I run it with -E '/usr/local/bin/cmatrix -b -s' (it looks better with -b on the dec vt220). It gives me the blinking cursor too.

 **EDIT**
I tried with an alias for the 'cmatrix -b -s' part but it gives the same issue of blinking cursor. 

This is OpenBSD 7.6-current with a vt220 attached via usb to serial FTDI  adapter. Then via null modem cable db25.
ttyU0   "/usr/libexec/getty std.19200"  vt220-w   on  secure

regards
Dylan

**Comment by mezantrop** [comment]
Checking. I also see issues on FreeBSD if running from ttyvN.

**UPD**. Hold on, I start to understand what could be wrong: my ANSI ESC sequences for getting cursor position / screen size do not work in console.

**Comment by mezantrop** [comment]
Try again, please. I have no OpenBSD currently, but on FreeBSD it works much better now.

**Comment by TheWanderer1983** [comment]
Just tried, now i'm getting the blinking cursor for anything i execute. 
For example just running ./sclocka -i 1 gives me a blinking non responsive cursor which i have to kill .
./sclocka -i 1 -E "/usr/local/bin/cmatrix -b -s " is giving the same. 
Previously ./sclocka -i 1 -E /usr/local/bin/cmatrix would get me a running cmatrix, but I couldn't exit out because it wasn't in screensaver mode. Now i just get the blinking cursor which needs killing to stop.

**Comment by mezantrop** [comment]
Yes, I installed OpenBSD and got the same. I missed to add or, perhaps, lost `FD_ZERO()` at some point. It must be done before starting to monitor file-descriptors. OpenBSD does not forgive such mistakes. I'm sorry, this took so much time, but I hope to fix the problem now and you can try testing.

Yes, I agree, cmatrix should be started in screensaver mode: `/usr/local/bin/cmatrix -b -s `

**Comment by TheWanderer1983** [comment]
Thank you for working on this, i'm happy to help. Just let me know when to pull again and i'll give it a try.

**Comment by mezantrop** [comment]
You can try now. The last change should fix the issue.
Btw, would you like to be mentioned in the contributors list for testing?

**Comment by TheWanderer1983** [comment]
Same as before. No change. 
Sure, you can add me if you like.

regards
Dylan

**Comment by mezantrop** [comment]
MMMM, now this is strange. It should work, I have fixed the stupid issue with `FD_ZERO()` macros :)
Here is Virtualbox with the freshly installed OpenBSD-7.6 - not current, just grabbed it from downloads and installed.

![sclocka-obsd](https://github.com/user-attachments/assets/6684ac6f-9f5e-453d-811a-918e2c403c2d)

UPD: https://github.com/mezantrop/sclocka/blob/master/CONTRIBUTORS.md updated. If you like, I can add more info and links to your profile, just give me them.

**Comment by TheWanderer1983** [comment]
Okay, I deleted the sclocka folder and cloned it again. This time it no longer get stuck at the blinking cursor. It waits the one minute and the screen goes blank like its about to start the matrix rain, but it exits out to console before anything starts scrolling down the screen. Afterwards if it type exit, instead of logging out it takes me back to console and requires a second exit to logout.

**Comment by mezantrop** [comment]
Do you specify the path to cmatrix correctly? Did you try the default screensavers show with dots on the black screen?

> Afterwards if it type exit, instead of logging out it takes me back to console and requires a second exit to logout.

That is correct. Sclocka starts a shell and gives the prompt to the user. Then if the user doesn't do any input within a time period, it starts the show - embedded one or external. When a user presses a key or the external saver exits, the user goes back  to the shell. To log out, the user has to exit this shell and the original shell.

If PAM is compiled and available in the system, after the screensaver show ends and before getting into the shell, the PAM procedures start.

**Comment by TheWanderer1983** [comment]
Should of checked with default.
./sclocka -i 1 
gives me Floating point exception (core dumped).

**Comment by mezantrop** [comment]
`./sclocks -h`
TERM variable is vt220 ?

UPD. Key points to mention: actual version 1.1.2 ; in `sclocka.c` check:

Lines 228, 229:
```
        sx = win.ws_col;
        sy = win.ws_row;

```
Line 274:
`        FD_ZERO(&rfd);
`

**Comment by TheWanderer1983** [comment]
echo $TERM = vt220
./sclocks -h 
v1.1.2
Those lines are there.

**Comment by mezantrop** [comment]
Then, could you share the core dump with me?

**Comment by TheWanderer1983** [comment]
Emailed it over.

**Comment by mezantrop** [comment]
All works now with -r key
